CUDA_VISIBLE_DEVICES=0 deepspeed --master_port 520 train.py \
                --train_path data/train_data.jsonl \
                --test_path data/test_data.jsonl \
                --model_name_or_path /root/autodl-tmp/ChatGLM3-Finetuning/cache/ZhipuAI/chatglm3-6b \
                --per_device_train_batch_size 1 \
                --max_len 1560 \
                --max_src_len 1024 \
                --learning_rate 1e-4 \
                --weight_decay 0.1 \
                --epochs 2 \
                --gradient_accumulation_steps 4 \
                --warmup_ratio 0.1 \
                --train_type lora \
                --lora_module_name "query_key_value" \
                --ds_file deepspeed/ds_zero2_no_offload.json \
                --gradient_checkpointing \
                --output_dir ./output